#!/bin/bash -x

mkdir -p ${dir}/alignments
OUT=${dir}/alignments/blastn.vs_canu${from}.${to}.out


if [ -f $OUT ]; then
   echo "$OUT exists, skipping..."
else 
   echo "RUNNING BLAST..."

   QUERY=$in.$from.$to

   from2=$((from*2))
   to2=$((to*2))

   sed -n "$((from2-1)),${to2}p;$((to2+1))q" $in > $QUERY
   
   module load blast+/2.7.1

   blastn \
    -query $QUERY -db $db -out $OUT \
    -outfmt 6' std qlen slen gaps qseq sseq sframe' \
    -evalue 1e-35 \
    -num_threads $threads \
    -max_target_seqs 10 \
    -max_hsps 5

   rm $QUERY

fi

